language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t shooreshg/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true shooreshg/react-test npm test

after_success:
    - docker build -t shooreshg/multi-client ./client 
    - docker build -t shooreshg/multi-nginx ./nginx
    - docker build -t shooreshg/multi-server ./server 
    - docker build -t shooreshg/multi-worker ./worker 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push shooreshg/multi-client
    - docker push shooreshg/multi-nginx
    - docker push shooreshg/multi-server
    - docker push shooreshg/multi-worker

deploy:
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    provider: elasticbeanstalk
    region: eu-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-2-453259886180
    bucket_path: docker-multi
    on:
        branch: master
    




